MaterialTrackerSite/MaterialTrackerApp/urls.py
from django.contrib import admin
from django.urls import path
from MaterialTrackerApp import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'MaterialTrackerApp'


urlpatterns = [
    path('', views.index, name='index'),
    path('inventory/', views.InventoryView.as_view(), name='inventory'),
    path('about/', views.about, name='about'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_item/', views.add_item, name='add_item'),
    path('add_item_success/', views.add_item_success, name='add_item_success'),
    path('add_item_fail/', views.add_item_fail, name='add_item_fail'),
    path('edit_item/<int:pk>', views.edit_item, name='edit_item'),



    path("material/list/", views.MaterialView.as_view(), name='material-list'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MaterialTrackerSite/MaterialTrackerSite/urls.py
from django.contrib import admin
from django.urls import path
from MaterialTrackerApp import views
from MaterialTrackerApp.models import *
from django.urls.conf import include
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from MaterialTrackerSite.views import *
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from rest_framework import routers
from rest_framework import permissions
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from drf_yasg.views import get_schema_view as yasg_schema_view
from drf_yasg import openapi

schema_view = yasg_schema_view(
    openapi.Info(
        title="API MaterialTracker",
        default_version='v1',
        description="API for materials",
        contact=openapi.Contact(email="lucastoscanop@gmail.com"),
        license=openapi.License(name='GNU GPLv3'),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    
    # Access control -------------------------------------------------------------
    # path('accounts/', include('accounts.urls')),
    path('docs/', include_docs_urls(title='Documentação da API')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/v1/', include(routers.DefaultRouter().urls)),
    path('openapi', get_schema_view(
        title="API material", 
        description="API to fetch material data",), 
        name='openapi-schema'
    ),
    #-----------------------------------------------------------------------------


    path('security/', LoginView.as_view(template_name='security/login.html') , name='sec-login'),
    path('security/register/', views.register , name='register'),
    path('security/logout/', views.logout , name='sec-logout'),
    path('logout/', LogoutView.as_view(next_page = reverse_lazy('sec-login')) , name='logout'),
    path('security/password_change/',
        PasswordChangeView.as_view(
        template_name='security/password_change_form.html', 
        success_url=reverse_lazy('sec-password_change_done'),
        ),
        name='sec-password_change'
    ),
    path('security/password_change_done/',
        PasswordChangeDoneView.as_view(
        template_name='security/password_change_done.html',
        ),
        name='sec-password_change_done'
    ),
    path('security/terminaRegistro/<int:pk>/', 
        MeuUpdateView.as_view(
        template_name='security/user_form.html',
        success_url=reverse_lazy('sec-login'),
        model=User,
        fields=[
        'first_name',
        'last_name',
        'email',
        ],
        ), name='sec-completaDadosUsuario'
    ),
    path('security/addProfilePhoto/<int:pk>/',
        MyAddProfilePhoto.as_view(
        template_name='security/addProfilePhoto.html',
        success_url=reverse_lazy('sec-login'),
        model=UserProfile,
        fields=[
        'avatar',
        ],
        ), name='sec-addProfilePhoto'
    ),

    path('security/password_reset/', PasswordResetView.as_view(
        template_name='security/password_reset_form.html', 
        success_url=reverse_lazy('sec-password_reset_done'),
        html_email_template_name='security/password_reset_email.html',
        subject_template_name='security/password_reset_subject.txt',
        from_email='webmaster@meslin.com.br',
        ), name='password_reset'
    ),
    path('security/password_reset_done/', PasswordResetDoneView.as_view(
        template_name='security/password_reset_done.html',
        ), name='sec-password_reset_done'
    ),
    path('security/password_reset_confirm/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
        template_name='security/password_reset_confirm.html', 
        success_url=reverse_lazy('sec-password_reset_complete'),
        ), name='password_reset_confirm'
    ),
    path('security/password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='security/password_reset_complete.html'
        ), name='sec-password_reset_complete'
    ),
    path('security/user_page', views.userPage, name='sec-user_page'),
    
    path('', include('MaterialTrackerApp.urls')),
    path('accounts/', include('accounts.urls')),
]

MaterialTrackerSite/accounts/urls.py
from django.urls import path
from accounts import views
from django.urls import include

app_name = 'accounts'

urlpatterns = [
    path('', include('MaterialTrackerApp.urls')),
    path('token-auth/', views.CustomAuthToken.as_view(), name='token-auth'),
    path('register/', views.CustomRegisterUser.as_view(), name='register'),
]

MaterialTrackerSite/MaterialTrackerApp/views.py
import csv

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import View
from django.contrib import messages 

from MaterialTrackerApp.models import *
from django.urls import reverse
from random import *
import json
from django.http import JsonResponse
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from rest_framework.views import APIView
from MaterialTrackerApp.serializers import MTMaterialSerializer
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework import status

@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
class MaterialView(APIView):
    @swagger_auto_schema(
        operation_summary="Get all materials",
        operation_description="Get all materials",
        responses={200: MTMaterialSerializer(many=True)}
    )
    def get(self, request):
        queryset = Material.objects.all()
        serializer = MTMaterialSerializer(queryset, many=True)
        print("serializer.data = " + str(serializer.data))
        return Response(serializer.data)

    @swagger_auto_schema(
        operation_summary="Delete selected materials",
        operation_description="Delete materials based on selected IDs",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                'selectedItems': openapi.Schema(
                    type=openapi.TYPE_ARRAY,
                    items=openapi.Items(type=openapi.TYPE_INTEGER),
                    description='List of material IDs to delete'
                )
            }
        ),
        responses={
            204: 'No Content',
            404: 'Not Found'
        }
    )
    def delete(self, request):
        id_erro = ""
        erro = False

        selected_items = request.data.get("selectedItems", [])
        print("Selected items:", selected_items)

        for id in selected_items:
            mat = Material.objects.filter(id=id).first()
            if mat:
                mat.delete()
            else:
                id_erro += str(id) + " "
                erro = True

        if erro:
            return Response({'error': f'item(s) [{id_erro.strip()}] not found'}, status=status.HTTP_404_NOT_FOUND)
        else:
            return Response(status=status.HTTP_204_NO_CONTENT)


def index(request):
    return render(request, 'MaterialTrackerApp/index.html')

def about(request):
    return render(request, 'MaterialTrackerApp/about.html')

@login_required
def dashboard(request):

    if request.method == 'GET':
        materials = Material.objects.all()
        user_projects_id = ProjectUser.objects.filter(user=request.user).values_list('project', flat=True)
        # other_user_projects = Project.objects.filter(pk__in=user_projects_id).exclude(pk=current_project_pk)

        context = {
            'materials': materials,
            # 'other_user_projects': other_user_projects,
            'columns': ["Ref", "Description", "Capacity", "Project", "Location", "Quality Exp Date", "Cost"]
        }
        return render(request, 'MaterialTrackerApp/project.html', context)

    elif request.method == 'POST':
        form_id = request.POST.get('form_id')
        if form_id == 'project_choice_form':
            return redirect('MaterialTrackerApp:project', current_project_pk=request.POST.get('selected_project'))

class InventoryView(LoginRequiredMixin, View):
    template_name = 'MaterialTrackerApp/inventory.html'


    def get(self, request):
        materials = Material.objects.all()
        context = {
            'materials': materials,
            'columns': ["Ref", "Description", "Capacity", "Project", "Location", "Quality Exp Date", "Cost"]
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        if request.method == 'POST':
            try:
                data = json.loads(request.body)
                action = data.get('action') 
                selected_items = data.get('selectedItems', [])

                if action == 'delete':
                    from .models import Material
                    Material.objects.filter(id__in=selected_items).delete()
                    return JsonResponse({'status': 'success', 'message': 'Items deleted successfully!'})

                elif action == 'request':
                    from .models import Material
                    context = {
                        'items': Material.objects.filter(id__in = selected_items),
                    }
                    return render(request, 'MaterialTrackerApp/new_request_finish.html', context)
                
                
                elif action == 'edit':
                    print(f"Action: {action}, Selected Items: {selected_items}")

                    from .models import Material
                    context = {
                        'items': Material.objects.filter(id__in = selected_items),
                    }
                    print(f'Editing items: {context["items"]}')
                    return HttpResponseRedirect(f"MaterialTrackerApp:edit_item")
                
                else:
                    return JsonResponse({'status': 'error', 'message': 'Unknown action'}, status=400)
            except Exception as e:
                return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
        else:
            return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)


        # if request.POST['action'] == 'request':
        #     return render(request, 'MaterialTrackerApp/new_request_finish.html')
        
        # elif request.POST['action'] == 'edit':
        #     print("Editing")
        #     material_id = request.POST['id']
        #     return redirect('MaterialTrackerApp:edit_item', pk=material_id)

        # elif  request.POST['action'] == 'delete':
        #     print("Deleting")
        #     print(request.POST['id'])
        #     Material.objects.filter(pk=request.POST['id']).delete()
        #     return redirect('MaterialTrackerApp:inventory')
        
        # elif request.POST['action'] == 'restart_db':
        #     from django.contrib import admin
        #     import os

        #     projs = Project.objects.all()
        #     locations = Location.objects.all()
        #     capacities = [20, 30, 40, 50, 60, 70, 80, 90, 100]
        #     print("curr_dir = " + os.getcwd())
        #     imgs = os.listdir("./MaterialTrackerApp/static/img/MaterialTrackerApp/material")
        #     currencies = Currency.objects.all()

        #     upper_bound = 100
        #     Material.objects.all().delete()
        #     for i in range(0, upper_bound):
        #         Material.objects.create(
        #             ref=f"ABC_{i}",
        #             description=f"Description {i}",
        #             capacity=choice(capacities),
                    
        #             project=choice(projs),
        #             main_img=choice(imgs),
        #             current_location=choice(locations),
        #             quality_exp_date=timezone.now(),
        #             cost=randrange(100, 10000),
        #             currency=choice(currencies),

        #             created_at=timezone.now(),
        #             updated_at=timezone.now()
        #         )

        #     return redirect('MaterialTrackerApp:inventory')


@login_required
def add_item(request):
    if request.method == 'GET':
        projects = Project.objects.all()
        locations = Location.objects.all()
        currency = Currency.objects.all()

        context = {
            'projects': projects,
            'locations': locations,
            'currencies': currency,
            'capacities': [20, 30, 40, 50, 60, 70, 80, 90, 100],
        }
        return render(request, 'MaterialTrackerApp/add_item.html', context)
    elif request.method == 'POST':
        if request.POST.get('action') == 'cancel':
            return redirect('MaterialTrackerApp:inventory')
        elif request.POST.get('action') == 'save':
            # Get data from the POST request
            reference = request.POST.get('reference')
            description = request.POST.get('description')
            capacity = request.POST.get('capacity')
            project = Project.objects.get(id=request.POST.get('project'))
            location = Location.objects.get(id=request.POST.get('current_location'))
            cost = request.POST.get('cost')
            currency = Currency.objects.get(id=request.POST.get('currency'))
            quality_exp_date = request.POST.get('quality_exp_date')
            photo = request.FILES.get('photo')  # Assuming photo is uploaded as a file

            print("reference = " + str(reference))
            print("description = " + str(description))
            print("capacity = " + str(capacity))
            print("project = " + str(project))
            print("location = " + str(location))
            print("cost = " + str(cost))
            print("currency = " + str(currency))
            print("quality_exp_date = " + str(quality_exp_date))
            print("photo = " + str(photo))

            # Validate the required fields
            if not reference or not description or not capacity or not project:
                messages.error(request, "Please fill out all required fields.", extra_tags='latest')
                return  render(request, 'MaterialTrackerApp/add_item.html')
            

MaterialTrackerSite/MaterialTrackerApp/templates/MaterialTrackerApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {%block head %}{% endblock %}


    <link rel="icon" href="{% static 'img/MaterialTrackerApp/mt_icon-removebg-preview.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/MaterialTrackerApp/general.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <script src="{% static 'js/MaterialTrackerApp/base.js' %}"></script>
    
    
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body>
    <div class="d-flex flex-column min-vh-100 w-100 mx-1">
        <header class="p-3 mb-3 border-bottom">

            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/">
                        <img src="{% static 'img/MaterialTrackerApp/mt_logo_no_bkg.png' %}" alt="Material Tracker"
                            height="40">
                    </a>

                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ms-3">
                        <li><a href="/" class="nav-link px-2 link-body-emphasis">Home</a></li>
                        <li><a href="{% url 'MaterialTrackerApp:inventory' %}"
                                class="nav-link px-2 link-body-emphasis">Inventory</a></li>
                        <li><a href="{% url 'MaterialTrackerApp:dashboard' %}"
                                class="nav-link px-2 link-body-emphasis">Dashboard</a></li>
                        <li><a href="{% url 'MaterialTrackerApp:about' %}"
                                class="nav-link px-2 link-body-emphasis">About</a></li>
                    </ul>




                    <div class="dropdown text-end">
                        <a href="#"
                            class="d-block link-body-emphasis text-decoration-none dropdown-toggle d-flex align-items-center"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.is_authenticated %}
                            <img src="{{ user.userprofile.avatar.url }}" alt="profile photo" width="32" height="32"
                                class="rounded-circle me-2">
                            <span>{{ user.get_username }}</span>
                            {% else %}
                            <img src="{% static 'img/MaterialTrackerApp/generic_user.png' %}" alt="generic user"
                                width="32" height="32" class="rounded-circle me-2">
                            {% endif %}
                        </a>

                        <ul class="dropdown-menu text-small">
                            {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="{% url 'sec-user_page' %}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'sec-logout' %}">Sign out</a></li>

                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'sec-login' %}">Sign in</a></li>
                            <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>

                </div>
            </div>
        </header>

        {% block content %}{% endblock %}
        
        <footer class="footer d-flex flex-wrap justify-content-between align-items-center py-1 my-1 mx-1 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-body-secondary" href="https://github.com/LucasToscanou/MaterialTracker"
                        target="_blank">
                        <svg width="26" height="26" viewBox="0 0 32 32" fill="currentColor">
                            <title>GitHub</title>
                            <path
                                d="M16 1.375c-8.282 0-14.996 6.714-14.996 14.996 0 6.585 4.245 12.18 10.148 14.195l0.106 0.031c0.75 0.141 1.025-0.322 1.025-0.721 0-0.356-0.012-1.3-0.019-2.549-4.171 0.905-5.051-2.012-5.051-2.012-0.288-0.925-0.878-1.685-1.653-2.184l-0.016-0.009c-1.358-0.93 0.105-0.911 0.105-0.911 0.987 0.139 1.814 0.718 2.289 1.53l0.008 0.015c0.554 0.995 1.6 1.657 2.801 1.657 0.576 0 1.116-0.152 1.582-0.419l-0.016 0.008c0.072-0.791 0.421-1.489 0.949-2.005l0.001-0.001c-3.33-0.375-6.831-1.665-6.831-7.41-0-0.027-0.001-0.058-0.001-0.089 0-1.521 0.587-2.905 1.547-3.938l-0.003 0.004c-0.203-0.542-0.321-1.168-0.321-1.821 0-0.777 0.166-1.516 0.465-2.182l-0.014 0.034s1.256-0.402 4.124 1.537c1.124-0.321 2.415-0.506 3.749-0.506s2.625 0.185 3.849 0.53l-0.1-0.024c2.849-1.939 4.105-1.537 4.105-1.537 0.285 0.642 0.451 1.39 0.451 2.177 0 0.642-0.11 1.258-0.313 1.83l0.012-0.038c0.953 1.032 1.538 2.416 1.538 3.937 0 0.031-0 0.061-0.001 0.091l0-0.005c0 5.761-3.505 7.029-6.842 7.398 0.632 0.647 1.022 1.532 1.022 2.509 0 0.093-0.004 0.186-0.011 0.278l0.001-0.012c0 2.007-0.019 3.619-0.019 4.106 0 0.394 0.262 0.862 1.031 0.712 6.028-2.029 10.292-7.629 10.292-14.226 0-8.272-6.706-14.977-14.977-14.977-0.006 0-0.013 0-0.019 0h0.001z">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-body-secondary"
                        href="https://www.linkedin.com/in/lucas-toscano-pimentel-appolin%C3%A1rio-cerqueira/"
                        target="_blank">
                        <svg width="36" height="36" viewBox="0 0 32 32" fill="currentColor">
                            <path
                                d="M18.72 3.99997H5.37C5.19793 3.99191 5.02595 4.01786 4.86392 4.07635C4.70189 4.13484 4.55299 4.22471 4.42573 4.34081C4.29848 4.45692 4.19537 4.59699 4.12232 4.75299C4.04927 4.909 4.0077 5.07788 4 5.24997V18.63C4.01008 18.9901 4.15766 19.3328 4.41243 19.5875C4.6672 19.8423 5.00984 19.9899 5.37 20H18.72C19.0701 19.9844 19.4002 19.8322 19.6395 19.5761C19.8788 19.32 20.0082 18.9804 20 18.63V5.24997C20.0029 5.08247 19.9715 4.91616 19.9078 4.76122C19.8441 4.60629 19.7494 4.466 19.6295 4.34895C19.5097 4.23191 19.3672 4.14059 19.2108 4.08058C19.0544 4.02057 18.8874 3.99314 18.72 3.99997ZM9 17.34H6.67V10.21H9V17.34ZM7.89 9.12997C7.72741 9.13564 7.5654 9.10762 7.41416 9.04768C7.26291 8.98774 7.12569 8.89717 7.01113 8.78166C6.89656 8.66615 6.80711 8.5282 6.74841 8.37647C6.6897 8.22474 6.66301 8.06251 6.67 7.89997C6.66281 7.73567 6.69004 7.57169 6.74995 7.41854C6.80986 7.26538 6.90112 7.12644 7.01787 7.01063C7.13463 6.89481 7.2743 6.80468 7.42793 6.74602C7.58157 6.68735 7.74577 6.66145 7.91 6.66997C8.07259 6.66431 8.2346 6.69232 8.38584 6.75226C8.53709 6.8122 8.67431 6.90277 8.78887 7.01828C8.90344 7.13379 8.99289 7.27174 9.05159 7.42347C9.1103 7.5752 9.13699 7.73743 9.13 7.89997C9.13719 8.06427 9.10996 8.22825 9.05005 8.3814C8.99014 8.53456 8.89888 8.6735 8.78213 8.78931C8.66537 8.90513 8.5257 8.99526 8.37207 9.05392C8.21843 9.11259 8.05423 9.13849 7.89 9.12997ZM17.34 17.34H15V13.44C15 12.51 14.67 11.87 13.84 11.87C13.5822 11.8722 13.3313 11.9541 13.1219 12.1045C12.9124 12.2549 12.7546 12.4664 12.67 12.71C12.6465 12.7725 12.6337 12.838 12.6325 12.9043C12.6313 12.9705 12.6416 13.0367 12.663 13.0997V17.34H10.66C10.66 17.34 10.69 10.96 10.66 10.21H12.67V11.13C12.9865 10.5989 13.4782 10.2138 14.04 10.06C14.5019 9.94593 14.9831 9.97372 15.43 10.14C15.8774 10.3223 16.2538 10.633 16.5 11.03C16.8941 11.6243 17.0883 12.3427 17.05 13.07V17.34H17.34Z">
                            </path>
                        </svg>
                    </a>
                </li>
            </ul>

        </footer>
    </div>
</body>

</html>

MaterialTrackerSite/MaterialTrackerApp/templates/MaterialTrackerApp/inventory.html
{% extends 'MaterialTrackerApp/base.html' %}
{% load static %}

{%block head %}
<title>Inventory</title>

<script src="{% static 'js/MaterialTrackerApp/inventory.js' %}"></script>
{% endblock %}


{% block content %}

<div class="d-flex align-items-center justify-content-between gap-3 mb-0 mx-5">
  <h1 class="display-5 fw-bolder text-body-emphasis me-auto">Inventory</h1>

  {% if messages %}
  {% for message in messages %}
  {% if 'latest' in message.tags %}
  <div
    class="alert {% if 'success' in message.tags %}alert-success{% elif 'error' in message.tags %}alert-danger{% elif 'warning' in message.tags %}alert-warning{% else %}alert-info{% endif %}">
    {{ message }}
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}



  <meta name="csrf-token" content="{{ csrf_token }}">
  <p class="mb-0" id="qty-selected"></p>
  <p class="datetime mb-0">Last update: {% now "Y-m-d H:i:s" %}</p>
  <a href="{% url 'MaterialTrackerApp:add_item' %}" class="btn btn-primary">Add item</a>

  <button type="button" class="btn btn-primary" id="request-selection-btn">
    Request Selection
  </button>
  <button type="button" class="btn btn-primary" id="edit-selection-btn">
    Edit Selection
  </button>
  <button type="button" class="btn btn-danger" id="delete-selection-btn">
    Delete Selection
  </button>
  
  <form method="post" action="">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" name="action" value="restart_db">Restart Dabase</button>
  </form>

</div>

<hr />
<div class="table-responsive">
  <table class="table table-striped table-sm table-hover">
    <thead>
      <tr>
        <th scope="col">
          <button class="btn btn-secondary" id="clear-btn">Clear</button>
        </th>
        <th scope="col">Photo</th>

        {% for col in columns %}
        <th scope="col">
          <div class="dropdown text-end">
            <a href="#"
              class="d-block link-body-emphasis text-decoration-none dropdown-toggle d-flex align-items-center"
              data-bs-toggle="dropdown" aria-expanded="false">
              <span>{{col}}</span>
            </a>

            <ul class="dropdown-menu text-small">
              <li><a class="dropdown-item" href="#">Sort ascending</a></li>
              <li><a class="dropdown-item" href="#">Sort descending</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <form class="dropdown-item d-flex align-items-center">
                  <input type="text" class="form-control me-2" id="inlineFormInputName" placeholder="">
                  <button type="submit" class="btn btn-primary">Filter</button>
                </form>
              </li>
            </ul>
            
          </div>
        </th>
        {% endfor %}

        <th scope="col">
        </th>

      </tr>
    </thead>
    <tbody>
      {% for material in materials%}
      <tr>
        <td>
          <input type="checkbox" id="{{ material.pk }}" class="checkbox" name="body_check_box" value="{{ material.pk }}">
        </td>
        <td>
          <img src="{{ material.main_img.url }}" class="border rounded justify-content-center" style="height: 100px;" alt="Material Image">
        </td>
        <td>{{material.ref}}</td>
        <td>{{material.description}}</td>
        <td>{{material.capacity}}</td>
        <td>{{material.project}}</td>
        <td>{{material.current_location}}</td>
        <td>{{material.quality_exp_date}}</td>
        <td>{{material.cost}} {{material.currency}}</td>
        <td>
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ material.pk }}">
            <input type="submit" class="btn btn-secondary" id="edit-btn" name="action" value="edit">
            <input type="submit" class="btn btn-secondary" id="edit-btn" name="action" value="request">
            <input type="submit" class="btn btn-secondary" id="edit-btn" name="action" value="delete">
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}