MaterialTrackerSite/MaterialTrackerApp/urls.py
from django.contrib import admin
from django.urls import path
from MaterialTrackerApp import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'MaterialTrackerApp'


urlpatterns = [
    path('', views.index, name='index'),
    path('inventory/', views.InventoryView.as_view(), name='inventory'),
    path('about/', views.about, name='about'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_item/', views.add_item, name='add_item'),
    path('add_item_success/', views.add_item_success, name='add_item_success'),
    path('add_item_fail/', views.add_item_fail, name='add_item_fail'),
    path('edit_item/<int:pk>', views.edit_item, name='edit_item'),



    path("material/list/", views.MaterialView.as_view(), name='material-list'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MaterialTrackerSite/MaterialTrackerSite/urls.py
from django.contrib import admin
from django.urls import path
from MaterialTrackerApp import views
from MaterialTrackerApp.models import *
from django.urls.conf import include
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from MaterialTrackerSite.views import *
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from rest_framework import routers
from rest_framework import permissions
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from drf_yasg.views import get_schema_view as yasg_schema_view
from drf_yasg import openapi

schema_view = yasg_schema_view(
    openapi.Info(
        title="API MaterialTracker",
        default_version='v1',
        description="API for materials",
        contact=openapi.Contact(email="lucastoscanop@gmail.com"),
        license=openapi.License(name='GNU GPLv3'),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    
    # Access control -------------------------------------------------------------
    # path('accounts/', include('accounts.urls')),
    path('docs/', include_docs_urls(title='Documentação da API')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/v1/', include(routers.DefaultRouter().urls)),
    path('openapi', get_schema_view(
        title="API material", 
        description="API to fetch material data",), 
        name='openapi-schema'
    ),
    #-----------------------------------------------------------------------------


    path('security/', LoginView.as_view(template_name='security/login.html') , name='sec-login'),
    path('security/register/', views.register , name='register'),
    path('security/logout/', views.logout , name='sec-logout'),
    path('logout/', LogoutView.as_view(next_page = reverse_lazy('sec-login')) , name='logout'),
    path('security/password_change/',
        PasswordChangeView.as_view(
        template_name='security/password_change_form.html', 
        success_url=reverse_lazy('sec-password_change_done'),
        ),
        name='sec-password_change'
    ),
    path('security/password_change_done/',
        PasswordChangeDoneView.as_view(
        template_name='security/password_change_done.html',
        ),
        name='sec-password_change_done'
    ),
    path('security/terminaRegistro/<int:pk>/', 
        MeuUpdateView.as_view(
        template_name='security/user_form.html',
        success_url=reverse_lazy('sec-login'),
        model=User,
        fields=[
        'first_name',
        'last_name',
        'email',
        ],
        ), name='sec-completaDadosUsuario'
    ),
    path('security/addProfilePhoto/<int:pk>/',
        MyAddProfilePhoto.as_view(
        template_name='security/addProfilePhoto.html',
        success_url=reverse_lazy('sec-login'),
        model=UserProfile,
        fields=[
        'avatar',
        ],
        ), name='sec-addProfilePhoto'
    ),

    path('security/password_reset/', PasswordResetView.as_view(
        template_name='security/password_reset_form.html', 
        success_url=reverse_lazy('sec-password_reset_done'),
        html_email_template_name='security/password_reset_email.html',
        subject_template_name='security/password_reset_subject.txt',
        from_email='webmaster@meslin.com.br',
        ), name='password_reset'
    ),
    path('security/password_reset_done/', PasswordResetDoneView.as_view(
        template_name='security/password_reset_done.html',
        ), name='sec-password_reset_done'
    ),
    path('security/password_reset_confirm/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
        template_name='security/password_reset_confirm.html', 
        success_url=reverse_lazy('sec-password_reset_complete'),
        ), name='password_reset_confirm'
    ),
    path('security/password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='security/password_reset_complete.html'
        ), name='sec-password_reset_complete'
    ),
    path('security/user_page', views.userPage, name='sec-user_page'),
    
    path('', include('MaterialTrackerApp.urls')),
    path('accounts/', include('accounts.urls')),
]

MaterialTrackerSite/accounts/urls.py
from django.urls import path
from accounts import views
from django.urls import include

app_name = 'accounts'

urlpatterns = [
    path('', include('MaterialTrackerApp.urls')),
    path('token-auth/', views.CustomAuthToken.as_view(), name='token-auth'),
    path('register/', views.CustomRegisterUser.as_view(), name='register'),
]

MaterialTrackerSite/MaterialTrackerSite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.views.generic.edit import UpdateView
from django.views import View

def register(request):
 if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('sec-login')
 else:
    form = UserCreationForm()
    context = {'form': form, }
    return render(request, 'security/register.html', context)

@login_required
def logout(request):
   return render(request,'security/logout.html')

class MeuUpdateView(UpdateView):
    def get(self, request, pk, *args, **kwargs):
        if request.user.id == pk:
            return super().get(request, pk, args, kwargs)
        else:
            return redirect('sec-login')

class MyAddProfilePhoto(UpdateView):
    def get(self, request, pk, *args, **kwargs):
        if request.user.id == pk:
            return super().get(request, pk, args, kwargs)
        else:
            return redirect('sec-login')

@login_required
def userPage(request):
    return render(request, 'security/user_page.html', {'user': request.user})

MaterialTrackerSite/MaterialTrackerSite/templates/security/addProfilePhoto.html
{% extends 'security/base.html' %}
{% block title %}Registro de Usuário{% endblock %}
{% block content %}
<h2>Complete os seus dados</h2>
<form method="post">
{% csrf_token %}
<table class="formulario">
{{ form.as_table }}
<tr>
<td></td>
<td><input type="submit" value="Atualiza"></td>
</tr>
</table>
</form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'MaterialTrackerSite/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'MaterialTrackerSite/css/general.css' %}">

    <link rel="icon" href="{% static 'img/MaterialTrackerApp/mt_icon-removebg-preview.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body>
    <div class="content">
        <div class="dev_navbar">
            <a href="{% url 'MaterialTrackerApp:index' %}" class="dev_nav-link">HomePage</a>

            {% if user.is_authenticated %}
            <a href="{% url 'sec-user_page' %}" class="dev_nav-link">Página do Usuário</a>
            {% else %}
            <a href="{% url 'register' %}" class="dev_nav-link">Registrar</a>
            {% endif %}

            <a href="{% url 'sec-login' %}" class="dev_nav-link user-info" title="Ir para o login">
                {% if user.is_authenticated %}
                Usuário: {{ user.username }}
                {% else %}
                Visitante
                {% endif %}
            </a>
        </div>
        {% block content %}{% endblock %}
    </div>
</body>

</html>

MaterialTrackerSite/MaterialTrackerSite/templates/security/login.html
{% extends 'security/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<h2>Página de Login</h2>

<div class="login-container">
    <form method="post">
        {% csrf_token %}
        <table class="formulario">
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    <div class="login-links">
        <a href="{% url 'password_reset' %}" class="dev_nav-link">Esqueceu a senha?</a>
        <a href="{% url 'register' %}" class="dev_nav-link">Registre-se</a>
    </div>
</div>

{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/logout.html
{% extends 'security/base.html' %}
{% block title %}Logout{% endblock %}
{% block content %}
 <h2>Página de Logout</h2>
 <form method="post"
 action="{% url 'logout' %}">
 {% csrf_token %}
 <input type="submit" value="Logout">
 </form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_change_done.html
{% extends 'security/base.html' %}
{% block title %}Senha Atualizada{% endblock %}
{% block content %}
<h2>Troca de senha</h2>
<p>Senha trocada com sucesso!</p>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_change_form.html
{% extends 'security/base.html' %}
{% block title %}Troca Senha{% endblock %}
{% block content %}
<h2>Página de Troca de Senha</h2>
<form method="post">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
        <tr>
            <td></td>
            <td><input type="submit" value="Troca senha"></td>
        </tr>
    </table>
</form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_reset_complete.html
{% extends 'security/base.html' %}
{% block title %}Senha Criada{% endblock %}
{% block content %}
<h2>Senha Criada</h2>
<p>Senha criada com sucesso!</p>
<p>Click
    <a href="{%url 'sec-login'%}?next={%url 'sec-secretPage'%}">
        aqui</a> para fazer login.
</p>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_reset_confirm.html
{% extends 'security/base.html' %}
{% block title %}Nova Senha{% endblock %}
{% block content %}
<h2>Página para Criar Nova Senha</h2>
{% if validlink %}
<form method="post">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
        <tr>
            <td></td>
            <td><input type="submit" value="Nova senha"></td>
        </tr>
    </table>
</form>
{% else %}
<p>Pedido inválido ou link expirado</p>
{% endif %}
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_reset_done.html
{% extends 'security/base.html' %}
{% block title %}Envio de Link{% endblock %}
{% block content %}
<h2>Reset de senha</h2>
<h3>Redefinição de senha enviada</h3>
<p>
    Enviamos-lhe instruções por e-mail para definir sua senha se
    existir uma conta com o e-mail digitado.
    Você deve recebê-las em breve.
</p>
<p>
    Se você não receber um e-mail, verifique se digitou o
    endereço com o qual se registrou e verifique sua pasta de
    spam.
</p>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_reset_email.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Recuperação de Senha de {{domain}}</title>
</head>

<body>
    <p>Alguém solicitou em {{ protocol }}://{{ domain }} email para {{ email }}
        de redefinição da senha da sua conta {{ user }}</p>
    <p>Por favor, acesse a seguinte página e escolha uma nova senha:</p>
    {% url 'password_reset_confirm' uidb64=uid token=token as link %}
    <p>
        <a href="{{ protocol}}://{{ domain }}{{ link }}">{{ protocol}}://{{ domain }}{{ link }}</a>
    </p>
    <p>Seu nome de usuário, caso tenha esquecido: <b>{{ user }}</b></p>
    <p>Obrigado por usar nosso site!</p>
    <p>Equipe {{ domain }}</p>
</body>

</html>

MaterialTrackerSite/MaterialTrackerSite/templates/security/password_reset_form.html
{% extends 'security/base.html' %}
{% block title %}Recuperar Senha{% endblock %}
{% block content %}
<h2>Página para Resetar a Senha</h2>
<form method="post">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
        <tr>
            <td></td>
            <td><input type="submit" value="Resetar a senha"></td>
        </tr>
    </table>
</form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/register.html
{% extends 'security/base.html' %}
{% block title %}Registro de Usuário{% endblock %}
{% block content %}
    <h2>Página de Registro</h2>
    <form method="post">
        {% csrf_token %}
        <table class="formulario">
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="Registrar"></td>
            </tr>
        </table>
    </form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/user_form.html
{% extends 'security/base.html' %}
{% block title %}Registro de Usuário{% endblock %}
{% block content %}
<h2>Complete os seus dados</h2>
<form method="post">
{% csrf_token %}
<table class="formulario">
{{ form.as_table }}
<tr>
<td></td>
<td><input type="submit" value="Atualiza"></td>
</tr>
</table>
</form>
{% endblock %}

MaterialTrackerSite/MaterialTrackerSite/templates/security/user_page.html
{% extends 'security/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<h2>Página do Usuário</h2>

<div class="user-actions">
    <button onclick="location.href='{% url 'sec-logout' %}'" class="dev_nav-button">Logout</button>
    <button onclick="location.href='{% url 'sec-password_change' %}'" class="dev_nav-button">Trocar senha</button>
    <button onclick="location.href='{% url 'sec-completaDadosUsuario' pk=user.id %}'" class="dev_nav-button">Finish your profile</button>
    <button onclick="location.href='{% url 'sec-addProfilePhoto' pk=user.id %}'" class="dev_nav-button">Add a photo to your profile</button>
</div>

{% endblock %}